language: node_js
node_js: 8.9.1
branches:
  only: master
cache: yarn
install: yarn
script:
  - yarn build
  - yarn test
deploy:
  api_key:
    secure: YdMY7aeOmUFnfjyAzWg5Qu3RBwN9zfY/u1oo+gCURIWKO1lRswVWX9UDRXNuVthV/XEF2YGpaeuGqBsNl+/3z4b5MQRpxkmJ3VarNPyKRCQIq4uSq3bnYVexO4OONi5fiH4SLelbFvIK1YmxEZfJPoWIbsRRCg6DJ+KIjqkRa/9Prd96ai9bCPlLBkIrTSWZZLNYqsmk/VD/QoYvK1r3VO9W0zQCLItVNq9lvEyUihx60SWeGF1ShVnszjjbuq7LDp+Pok3JqjEBjEOzNfNsda9xPXZIccdecCs2SNgO785OBEoT8JLN3ob/cw9H3QaqlLhRdBev6a/GtXuxflA5S5NmbZog5zeds0tOXXXwFWwU79bkKlmSQqVhRUpCNeDHW7gJq8cKiEG1ToUQHFYNG+j+rs4BuGcXbVeuZ6WUmSwADXKbI3MPKQ7BpdtGRr+uNLD1H1nAA781/7ub2HT8Dzfdgf+0It07gmWpOkpKlmEqd13cbZbFcTSM5cP0B4RldZc4IMXH8dkkuK/DL7R4Uqus9xXHp2g79K2mbY66hh7JYHU7Eq4f+BRjdrSt1g7/e+NgZN4hBOyyL5YR6meB97JY2nTmSWxV6HcAH7sRxN44L3mRIpD5XhbYCoeL+oVGi+U/pMYLrBQFOv3u91Cm+kk61ynFaQlJcFX36P6kcj0=
  email: npmjs@charlesstover.com
  on:
    branch: master
  provider: npm
  skip_cleanup: true
